use_frameworks!

target 'CEPSwift_Example' do
  pod 'CEPSwift', :path => '../'

  target 'CEPSwift_Tests' do
    pod 'CEPSwift', :path => '../'
    pod 'RxTest'

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
    
  end
end
