use_frameworks!

target 'CEPSwift_Example' do
  pod 'CEPSwift', :path => '../'

  target 'CEPSwift_Tests' do
    pod 'CEPSwift', :path => '../'

    pod 'Quick'
    pod 'Nimble'
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end