# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thesis' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'CEPSwift'
  # Pods for thesis

  target 'thesisTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
    # Pods for testing
  end

  target 'thesisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
