# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thesis' do
  pod 'CEPSwift', :path => '../'

  target 'thesisTests' do
    pod 'CEPSwift', :path => '../'
  end

end
