# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSuite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestSuite

  target 'TestSuiteTests' do
    inherit! :search_paths
    pod 'CEPSwift', :path => '../'
    pod 'Quick'
    pod 'Nimble'
    # Pods for testing
  end

end
